version: "3.9"
name: fetchrewards

services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
      - 4566:4566
  postgres:
    image: fetchdocker/data-takehome-postgres
    ports:
      - 7777:5432